version: "3"
services:
  docker-mongo:
    image: mongo:latest
    container_name: "docker-mongo"
    ports:
      - 27070:27017
    command: mongod --port 27070
  template-system-backend:
    image: template-system-backend:1.0.0
    container_name: "template-system-backend"
    ports:
      - 9000:8080
    links:
      - docker-mongo